version: "2"
services:
    web:
        build: .
        ports:
        - "8080:80"
        depends_on:
        - db
    db:
        command: mysqld --user=root --sql_mode=""
        image: mysql
        ports:
        - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_USER: dev
            MYSQL_PASSWORD: 123456
            MYSQL_DATABASE: theblog
            SQL_MODE: ""